hp_config:
  model:
    input_dim: 132
    output_dim: 15
    hidden_dims:
      - [128]
      - [64]
      - [128, 64]
      - [128, 64, 32]
      - [128, 128, 64]
      - [128, 64, 64]
      - [64, 64, 32]
      - [128, 64, 64, 32]
      - [64, 64, 32, 32]
  epochs: 60
  patience: 5
  batch_size: 8
  lr: [1.e-6, 1.e-3, loguniform]
experiment:
  id: MLP-2
  seed: 42
  n_trials: 100
  cpus_per_trial: 2
  gpus_per_trial: 0.2
dataset:
  name: SCVIC
  seed: 1
  n_worker: 1
  network_data: true
  host_data: false
  host_embeddings: false

