hp_config:
  model:
    encoder:
      n_layer: [1, 2, 4, 6, "choice"]
      head: null
      embedding: 102
      d_model: [32, 64, "choice"]
      n_head: [4, 8, "choice"]
      factor_dim_feedforward: [0.5, 1, 2, "choice"]
      dropout: 0.1
      max_len: 10
    head:
      output_dim: 2
      hidden_dims:
        - [256, 128]
        - [256, 128, 64]
        - [256, 64, 64]
        - [256, 128, 64, 64]
        - choice
  epochs: 40
  patience: 10
  batch_size: 16
  lr: [5.e-7, 1.e-4, loguniform]
experiment:
  id: MLP-OPTC-T-2
  seed: 42
  n_trials: 300
  cpus_per_trial: 3
  gpus_per_trial: 0.3
dataset:
  name: OpTC
  train:
    undersampling:
      target_dist: 
        0: 0.66
        1: 0.34
      seed: 12345
      online: false
    ds_name: hids-v5_201_eval_train
    parts: 8
    window_size: 10
    shuffle: true
    eval_mode: true
    stage: 5
  eval:
    undersampling:
      target_dist: 
        0: 0.66
        1: 0.34
      seed: 12345
      online: false
    ds_name: hids-v5_201_eval_eval
    parts: 8
    window_size: 10
    shuffle: false
    eval_mode: true
    stage: 5
