hp_config:
  model:
    n_estimators: [10, 50, 100, 200, 500, 1000, grid]
    max_features: [sqrt, log2, null, grid]
experiment:
  id: RF-1
  seed: 42
  cpus_per_trial: 16
  gpus_per_trial: 0
dataset:
  name: SCVIC
  seed: 1
  network_data: true
  host_data: false
  host_embeddings: false
  exclude: null
