hp_config:
  model:
    input_dim: 356
    output_dim: 2
    hidden_dims: [128, 128, 64]
  epochs: 30
  patience: 5
  lr: 2.e-5
experiment:
  id: DDoS-HOIC
  model_type: CMLP
  seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  device: [cuda:0, cuda:1, cuda:2]
  gpus_per_trial: 0.5
  cpus_per_trial: 2
dataset:
  ds_name: SCVIC
  random_state: 1
  num_workers: 2
  network_data: true
  host_data: true
  host_embeddings: false
  exclude: [DDOS-HOIC]
  batch_size: 8

