hp_config:
  model:
    encoder:
      n_layer: 1
      head: null
      embedding: 102
      d_model: 64
      n_head: 8
      dim_feedforward: 32
      dropout: 0.1
      max_len: 10
    head:
      input_dim: 640
      output_dim: 2
      hidden_dims: [256, 64, 64]
  epochs: 40
  patience: 10
  batch_size: 16
  lr: 9.e-5
experiment:
  id: MLP-OPTC-T-2
  model_type: MLPTransformer
  seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  device: [cuda:0, cuda:1, cuda:2]
  gpus_per_trial: 0.25
  cpus_per_trial: 3
dataset:
  name: OpTC
  train:
    undersampling:
      target_dist: 
        0: 0.66
        1: 0.34
      seed: 12345
      online: false
    ds_name: hids-v5_201_eval_train--104-170-205-255-321-355-419-462
    parts: 4
    only_benign: false
    window_size: 10
    shuffle: true
    eval_mode: true
    stage: 5
  eval:
    undersampling:
      target_dist: 
        0: 0.66
        1: 0.34
      seed: 12345
      online: false
    ds_name: hids-v5_201_eval_eval--503-559-609
    parts: 4
    only_benign: false
    window_size: 10
    shuffle: false
    eval_mode: true
    stage: 5
