hp_config:
  model:
    input_dim: 1690
    output_dim: 20
    hidden_dims:
      - 255
  epochs: 10
  patience: 5
  batch_size: 32
  lr: 1.e-6
experiment:
  id: MLPAE-OPTC-2
  model_type: MLPAE
  seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  device: [cuda:0, cuda:1]
  gpus_per_trial: 0.25
  cpus_per_trial: 2
dataset:
  ds_name: OpTC
  train:
    ds_name: cids-v5_201_traind
    parts: [0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15]
    last_part: 16
    window_size: 10
    shuffle: true
    only_benign: false
    eval_mode: false
    stage: 4
  eval:
    ds_name: cids-v5_201_train
    parts: [2, 7, 12]
    last_part: 16
    window_size: 10
    shuffle: false
    only_benign: true
    eval_mode: true
    stage: 4
