hp_config:
  model:
    input_dim: 132
    output_dim: 8
    hidden_dims:
      - 64
  epochs: 20
  patience: 5
  batch_size: 8
  lr: 4.5e-4
experiment:
  id: MLPAE-1
  model_type: MLPAE
  seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  device: [cuda:0, cuda:1, cuda:2]
  gpus_per_trial: 0.6
  cpus_per_trial: 2
dataset:
  ds_name: SCVIC
  seed: 1
  n_worker: 1
  network_data: true
  host_data: false
  host_embeddings: false
