hp_config:
  model:
    network:
      input_dim: 132
      output_dim: 15
      hidden_dims: [128, 64, 64]
    host:
      n_layer: 1
      head: null
      embedding: null
      d_model: 8
      n_head: [2, 4, 8, "choice"]
      factor_dim_feedforward: [0.5, 1, 2, "choice"]
      dropout: 0.1
      max_len: 28
    embedding:
      n_layer: 1
      head: [null, 8, 16, 32, "choice"]
      embedding: 768
      d_model: [128, 256, 512, "choice"]
      n_head: [8, 16, 32, "choice"]
      factor_dim_feedforward: [0.5, 1, 2, "choice"]
      dropout: 0.1
      max_len: 100
    aggregation:
      output_dim: 15
      hidden_dims: 
        - [512]
        - [256]
        - [512, 256]
        - [512, 64]
        - [256, 64, 32]
        - [512, 128, 64]
        - [256, 128, 128, 64]
        - "choice"
  epochs: 60
  patience: 5
  batch_size: 8
  lr: [1.e-6, 1.e-3, loguniform]
  alpha: [0., 1., uniform]
experiment:
  id: CIDS-1
  seed: 42
  n_trials: 500
  cpus_per_trial: 4
  gpus_per_trial: 0.33
dataset:
  ds_name: SCVIC
  seed: 1
  n_worker: 1
  network_data: true
  host_data: true
  host_embeddings: true

