hp_config:
  model:
    input_dim: 1690
    output_dim: 20
    hidden_dims:
      - 256
  epochs_pretraining: 10
  epochs_finetuning: 30
  patience: 5
  batch_size: 32
  lr: 1.e-6
  gamma: 1.
experiment:
  id: MLPAE-SSL-INV-1
  model_type: MLPAE
  loss_type: inverse
  seed: [1, 2, 3, 4, 5, 6, 7, 8, 9 ,10]
  device: [cuda:0, cuda:1]
  gpus_per_trial: 0.25
  cpus_per_trial: 2
  model_path: models/03_semisupervision/unsupervised/OpTC/MLPAE/201/MLPAE-SSL-INV-1-
dataset:
  ds_name: OpTC
  n_worker: 1
  unsupervised:
    train:
      ds_name: cids-v5_201_train-ff
      parts: [0, 1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14, 15]
      last_part: 16
      window_size: 10
      shuffle: true
      only_benign: true
      eval_mode: false
      stage: 4
    eval:
      ds_name: cids-v5_201_train-ff
      parts: [2, 7, 12]
      last_part: 16
      window_size: 10
      only_benign: false
      shuffle: false
      eval_mode: true
      stage: 4
  supervised:
    train:
      undersampling:
        target_dist: 
          0: 0.66
          1: 0.34
        seed: 12345
        online: false
      ds_name: cids-v5_201_eval-ff_train--104-170-205-255-321-355-419-462
      parts: 4
      only_benign: false
      window_size: 10
      shuffle: true
      eval_mode: true
      stage: 5
    eval:
      undersampling:
        target_dist: 
          0: 0.66
          1: 0.34
        seed: 12345
        online: false
      ds_name: cids-v5_201_eval-ff_eval--503-559-609
      parts: 4
      only_benign: false
      window_size: 10
      shuffle: false
      eval_mode: true
      stage: 5
